version: '3.9'

services:
  shared-health-record:
    image: ghcr.io/i-tech-uw/shared-health-record:${SHR_VERSION-latest}
    networks:
      - default
      - hapi-fhir
      - shr
      - kafka
      - opencr
    configs:
      - source: shr_config
        target: /app/config/config_docker.json
      - source: shr_mediator
        target: /app/config/mediator_docker.json
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
configs:
  shr_config:
    file: ./config/config.json
    labels:
      name: shr
  shr_mediator:
    file: ./config/mediator.json
    labels:
      name: shr

networks:
  default:
  kafka:
    external: true
    name: kafka_public
  hapi-fhir:
    external: true
    name: hapi-fhir_public
  shr:
    name: shr_public
    external: true
  opencr:
    name: opencr
    external: true
  default:
